server:
  port: 8080
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 5000
  datasource:
    url: jdbc:postgresql://localhost:5432/swi2
    username: postgres
    password: 12345678Aa+
  jpa:
    hibernate:
      ddl-auto: update